version: "3.2"

services:
  fast-api:
    container_name: fast-api
    build: ./
#    env_file: .env
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2000M

